security:
  basic:
    enabled: false
management:
  security:
    enabled: false
spring:
  data:
    mongodb:
      uri: mongodb://hediApps:uLqfGxxbJbiYCrzD@cluster0-shard-00-00-qm4w1.mongodb.net:27017,cluster0-shard-00-01-qm4w1.mongodb.net:27017,cluster0-shard-00-02-qm4w1.mongodb.net:27017/hediapps?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin
      #uri: mongodb://localhost:27017/hediapps?authSource=admin
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  application:
    name: uaa-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
  context-path: /uaa
  use-forward-headers: false